DROP DATABASE IF EXISTS "luxuryakka";

DROP ROLE IF EXISTS luxuryakka;

CREATE ROLE luxuryakka LOGIN
ENCRYPTED PASSWORD 'b3a7bff724584262b6340aa97263eda9'
SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

CREATE DATABASE "luxuryakka"
WITH OWNER = luxuryakka
ENCODING = 'UTF8'
TABLESPACE = pg_default
CONNECTION LIMIT = -1;